stages:
  - build
  - deploy

variables:
  DATABASE_URL: postgres://paymentuser:paymentpass@db:5432/paymentdb
  REACT_APP_API_URL: http://localhost:9902

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose build

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - main