version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3000

  mobile:
    build:
      context: .
      dockerfile: apps/mobile/Dockerfile
    ports:
      - "19006:19006"
    environment:
      - NODE_ENV=development
      - EXPO_PUBLIC_API_URL=http://backend:3000

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cashbook
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
