version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    environment:
      DATABASE_URL: postgres://paymentuser:paymentpass@db:5432/paymentdb
      PORT: 9902
    # Add other backend envs as needed
    ports:
      - "9902:9902"
    depends_on:
      - db

  web:
    build: ./apps/web
    environment:
      REACT_APP_API_URL: http://localhost:9902
      PORT: 9901
    # Add other frontend envs as needed
    ports:
      - "9901:9901"
    depends_on:
      - backend

volumes:
  pgdata: